services:
  backend:
    container_name: fastapi_backend
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-prod}
    volumes:
      - ./server:/app
    ports:
      - "5000:8000"
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    container_name: preact_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8000:5173"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
