"""remove unique constrate fer trade items

Revision ID: 1c6af7be9d4e
Revises: d4e391fe6bcf
Create Date: 2025-05-11 22:58:58.355633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6af7be9d4e'
down_revision: Union[str, None] = 'd4e391fe6bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trade_user_item_ids_unique', 'trade', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trade_user_item_ids_unique', 'trade', ['user_item_id_from', 'user_item_id_to'])
    # ### end Alembic commands ###
