name: Backend CI (FastAPI + Poetry)

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    name: Python FastAPI (Poetry)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      USE_TESTCONTAINERS: false
      DATABASE_MIGRATION_URL: ${{ secrets.DATABASE_MIGRATION_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      DATABASE_URL: postgresql+psycopg2://testuser:testpass@localhost:5432/testdb

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: poetry install --no-interaction --no-root

      - name: Run Ruff (linter + checker)
        run: poetry run ruff check .

      - name: Run MyPy (type checking)
        run: poetry run mypy .

      - name: Run Tests (pytest)
        run: poetry run pytest --cov=tests -vv
