name: Frontend CI (Preact)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  frontend:
    name: Node.js Preact
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --if-present

      - name: Run ESLint (Linter)
        run: npm run lint

      # - name: Run tests
      #   run: npm test
